[2020-06-21 21:07:38,699 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on / [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:07:38,699 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on / [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:07:38,961 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:07:38,961 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:07:39,055 ERROR] [in E:\python\venv\hting\lib\site-packages\werkzeug\_internal.py:113]
Error on request:
Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\Lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "E:\GitWorkplace\hting\application.py", line 47, in error_handler
    return render_template("error/503.html"), code
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/503.html
[2020-06-21 21:07:39,073 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:07:39,073 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:07:39,080 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:07:39,080 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:07:39,132 ERROR] [in E:\python\venv\hting\lib\site-packages\werkzeug\_internal.py:113]
Error on request:
Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\Lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "E:\GitWorkplace\hting\application.py", line 47, in error_handler
    return render_template("error/503.html"), code
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/503.html
[2020-06-21 21:08:02,065 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on /test/test0 [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:08:02,065 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on /test/test0 [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:08:02,072 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:08:02,072 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:08:02,119 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:08:02,119 ERROR] [in E:\python\venv\hting\lib\site-packages\flask\app.py:1891]
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html
[2020-06-21 21:08:02,128 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:08:02,128 ERROR] [in E:\GitWorkplace\hting\application.py:46]
Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

[2020-06-21 21:08:02,129 ERROR] [in E:\python\venv\hting\lib\site-packages\werkzeug\_internal.py:113]
Error on request:
Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\Lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "E:\GitWorkplace\hting\application.py", line 47, in error_handler
    return render_template("error/503.html"), code
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/503.html
[2020-06-21 21:08:02,173 ERROR] [in E:\python\venv\hting\lib\site-packages\werkzeug\_internal.py:113]
Error on request:
Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "E:\python\venv\hting\Lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1744, in handle_http_exception
    return handler(e)
  File "E:\GitWorkplace\hting\application.py", line 31, in page_not_found
    return render_template("error/404.html"), 404
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/404.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "E:\python\venv\hting\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "E:\python\venv\hting\Lib\site-packages\flask\app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "E:\GitWorkplace\hting\application.py", line 47, in error_handler
    return render_template("error/503.html"), code
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\python\venv\hting\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\python\venv\hting\Lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "E:\python\venv\hting\Lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error/503.html
